version: '3.4'

services:
  postgres:
    image: postgres
    restart: always
    ports: 
      - "5432:5432"
    environment:
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_DB=mydatabase
    networks:
      - mynetwork

  itemstore.webapi:
    image: ${DOCKER_REGISTRY-}itemstorewebapi
    restart: always
    build:
      context: .
      dockerfile: ItemStore.WebApi/Dockerfile
    environment:
      - "ConnectionStrings:PostgreConnection=host=postgres;port=5432;database=mydatabase;username=myuser;password=mypassword"
    depends_on:
      - postgres 
    networks:
      - mynetwork

networks:
  mynetwork: